//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Bolsa_Empleados.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrador
    {
        public int IDAdmin { get; set; }
        public string Nombre { get; set; }
        [DisplayName("Usuario")]
        [Required(ErrorMessage = "Campo vacio")]
        public string Usuario { get; set; }
        [Required(ErrorMessage = "Campo vacio")]

        [DataType(DataType.Password)]
        public string Contraseña { get; set; }
        public string Dirreccion { get; set; }
        public Nullable<int> idpais { get; set; }
        public string ErrorLogin { get; set; }

    }
}
